### ISSUE TITLE
Packet is too short, unable to read length fields. (IOError)

### ISSUE THREAD

**Issue by VeeanB** [IdleEngineers/xbee#1]
Hi,
while running check_and_set_destination_address.rb 
i am getting bellowed error
Transmitting frame: #<XBee::Frames::RemoteATCommandRequest:0x000000016ec570 @address16=#<XBee::Address16:0x00000001c04cd8 @bytes=[255, 254]>, @semantic_logger=#<SemanticLogger::Logger:0x00000001bfd000 @filter=nil, @name="XBee::Frames::RemoteATCommandRequest", @level_index=nil, @level=nil>, @packet=nil, @address64=#<XBee::Address64:0x00000001bfccb8 @bytes=[0, 19, 162, 0, 65, 81, 28, 254]>, @at_command=[78, 73], @id=1>
/home/veena/xbee/lib/xbee/packet.rb:109:in `rescue in from_byte_enum': Packet is too short, unable to read length fields. (IOError)
	from /home/veena/xbee/lib/xbee/packet.rb:105:in `from_byte_enum'
	from /home/veena/xbee/lib/xbee/xbee.rb:94:in `read_packet'
	from /home/veena/xbee/lib/xbee/xbee.rb:101:in `read_frame'
	from check_and_set_destination_address.rb:20:in `block (2 levels) in run'
	from check_and_set_destination_address.rb:19:in `loop'
	from check_and_set_destination_address.rb:19:in `block in run'
	from /home/veena/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /home/veena/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /home/veena/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /home/veena/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /home/veena/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from check_and_set_destination_address.rb:18:in `run'
	from check_and_set_destination_address.rb:161:in `<main>'

 Can anybody help me to come out of it
Thank you

**Comment by aarontc** [comment]
Hi @VeeanB - this sounds like you may have a communication issue with your xbee radio or a configuration issue. Can you post the configuration you're using as well as how you're connected?

**Comment by VeeanB** [comment]
Xbee information
Attention: OK
Firmware: 405F
Hardware: 2E48
Baud: 9600
Parity: None
Neighbors:
[{:MY=>"7249", :SH=>"0013A200", :SL=>"41511CFE", :DB=>0, :NI=>"FFFE"},
 {:MY=>"01", :SH=>"00", :SL=>"C105", :DB=>-4126, :NI=>"CAFE1001"}]
Node ID: ROOM 18
Channel: 12
PAN ID: 123FAB
MY: 7249
SH: 13A200
SL: 41511CFE
DH: 13A200
DL: 416747BD
Last received signal strength (dBm): 0
Port 0:
Port 1: Disabled
Port 2: Disabled
Port 3: Disabled
Port 4: Disabled
Port 5: Associated_Indicator
Port 6: Disabled
Port 7: CTS
Port 8:

This is code for Transmiting packets
require 'xbee'
xbee = XBee::XBee.new device_path: '/dev/ttyUSB0', rate: 9600
xbee.open
request = XBee::Frames::RemoteATCommandRequest.new
request.address64 = XBee::Address64.from_string '0013A20041511CFE'
request.at_command = 'NI'
request.id = 0x10
xbee.write_frame request
puts xbee.read_frame
xbee.close



Regards
Veena B
9880444819

**Comment by aarontc** [comment]
Have you verified the radio is in Escaped API mode? (Parameter AP == 0x02)

**Comment by VeeanB** [comment]
Yes its enable

Regards
Veena B
9880444819

**Comment by aarontc** [comment]
In that case I think we'll need to see the raw bytes from both sides of the conversation to diagnose where the bug is in the parsing code.

**Comment by VeeanB** [comment]
Okay ,
How can we read the raw bytes

Regards
Veena B
9880444819

**Comment by aarontc** [comment]
Any serial monitor tool will work. I use a logic analyzer physically connected to the appropriate pins on the xbee radio, but you can probably use kermit or another serial terminal tool to capture the streams. Just make sure only the raw bytes are captured and not the interpretation of terminal escape sequences, etc.

**Comment by VeeanB** [comment]
We have to specify any length fields

**Comment by aarontc** [comment]
Sorry but I don't understand your question.

**Comment by VeeanB** [comment]
rescue in from_byte_enum': Packet is too short, unable to read length fields. (IOError)
for this error we need to specify length field

**Comment by VeeanB** [comment]
#<XBee::Frames::ReceivePacket:0x000000000188bbd8>
I got this result after running transmit_packet.rb
but unable to get recieve_packet

**Comment by aarontc** [comment]
Sorry but we're not going to be able to help without a capture of the bytes going into the parser. Either the data is malformed or you've found a bug, but it's impossible to say which.

**Comment by VeeanB** [comment]
okay,
this is form read frames
I [14034:16011040] ReadFrames -- Frame received. --
{:frame=>#<XBee::Frames::ReceivePacket:0x0000000002460378
@semantic_logger=#<SemanticLogger::Logger:0x0000000002461980 @filter=nil,
@name="XBee::Frames::ReceivePacket", @level_index=nil, @level=nil>,
@packet=#<XBee::Packet:0x0000000002475db8 @data=[144, 0, 19, 162, 0, 65,
38, 133, 36, 0, 0, 1, 98]>, @parse_bytes=[], @frame_type=144,
@address64=#<XBee::Address64:0x0000000002457c28 @bytes=[0, 19, 162, 0, 65,
38, 133, 36]>, @address16=#<XBee::Address16:0x00000000024579d0 @bytes=[0,
0]>, @options=1, @data=[98]>}


Regards
Veena B
9880444819

**Comment by aarontc** [comment]
If the library was able to instantiate an `XBee::Frames::ReceivePacket`, then the parsing must have succeeded. I don't see how you could be getting the exception you are seeing. More information is required.
